# Generated by Django 4.2.5 on 2023-09-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appusers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
