# Generated by Django 4.2.5 on 2023-09-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apphome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listquestatual',
            options={'ordering': ['-date_publication']},
        ),
    ]
