# Generated by Django 4.2.5 on 2023-09-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assuntonome', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursonome', models.CharField()),
                ('eixonome', models.CharField(choices=[('COMP', 'Eixo de Computação'), ('LIC', 'Eixo de Licenciatura'), ('NEG', 'Eixo de Negócio')])),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtext', models.TextField()),
                ('qimagem', models.ImageField(upload_to='appquest/static/appquest/')),
                ('semana', models.IntegerField(choices=[(1, 'Semana 1'), (2, 'Semana 2'), (3, 'Semana 3'), (4, 'Semana 4'), (5, 'Semana 5'), (6, 'Semana 6'), (7, 'Semana 7')])),
                ('assuntoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appquest.assunto')),
                ('cursoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appquest.curso', verbose_name='Curso')),
            ],
        ),
        migrations.AddField(
            model_name='assunto',
            name='cursoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appquest.curso', verbose_name='Curso'),
        ),
        migrations.CreateModel(
            name='AltQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alttexto', models.TextField()),
                ('altcorreta', models.BooleanField()),
                ('altjustif', models.TextField()),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appquest.questions', verbose_name='Questão')),
            ],
        ),
    ]
