# Generated by Django 4.2.5 on 2023-09-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qimagem',
            field=models.ImageField(blank=True, upload_to='appquest/static/appquest/'),
        ),
    ]
