# Generated by Django 4.2.5 on 2023-09-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquest', '0003_alter_altquestion_altjustif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qimagem',
            field=models.ImageField(blank=True, upload_to='appquest'),
        ),
    ]
