# Generated by Django 4.2.5 on 2023-09-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appquest', '0004_alter_questions_qimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tipoquestao',
            field=models.IntegerField(choices=[(1, 'AVA'), (2, 'Texto Base'), (3, 'Videoaulas'), (4, 'Outras')], default=1),
            preserve_default=False,
        ),
    ]
