# Generated by Django 4.2.5 on 2023-09-27 00:42

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appquest', '0008_remove_questions_rspcorreta_questions_rspcorretaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='rspcorretaid',
            field=models.ForeignKey(limit_choices_to={'qid_id': builtins.id}, on_delete=django.db.models.deletion.CASCADE, to='appquest.altquestion', verbose_name='AltQuestion'),
        ),
    ]
