# Generated by Django 4.2.5 on 2023-09-29 00:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appquest', '0011_alter_questions_rspcorretaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qtext',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
