# Generated by Django 4.2.5 on 2023-10-02 16:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appquest', '0012_alter_questions_qtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qtext',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
